PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX qu: <http://purl.oclc.org/NET/ssnx/qu/qu#>
PREFIX dim: <http://purl.oclc.org/NET/ssnx/qu/dim#>
PREFIX aws: <http://purl.oclc.org/NET/ssnx/meteo/aws#>
PREFIX oeg-sen: <http://oeg-upm.net/onto/sensordemo/>
PREFIX cf-feature: <http://purl.oclc.org/NET/ssnx/cf/cf-feature#>

SELECT DISTINCT ?obs 
FROM NAMED STREAM <http://cwi.nl/SRBench/observations> [NOW - 1 HOURS]
WHERE {  
 ?obs ssn:observedBy [a aws:TemperatureSensor].
 ?obs ssn:observationResult [ssn:hasValue [qu:unit [a dim:TemperatureUnit]]].
}
