PREFIX om-owl: <http://knoesis.wright.edu/ssw/ont/sensor-observation.owl#>
PREFIX weather: <http://knoesis.wright.edu/ssw/ont/weather.owl#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX qu: <http://purl.oclc.org/NET/ssnx/qu/qu#>

SELECT DISTINCT ?observation ?sensor ?value  
FROM NAMED STREAM <http://cwi.nl/SRBench/observations> [NOW - 100 MS SLIDE 100 MS]
WHERE {
  ?observation ssn:observedBy ?sensor;
               ssn:observationResult ?result.
  ?result ssn:hasValue ?obsvalue.             
  ?obsvalue qu:numericalValue ?value.
  FILTER (?value > 0.5)  
}